# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59a49aacbcc730ef34edb3070f7a5090b44a025ad62dad8f5e0e723a1bf17e56095c98be44f8245cba5d463548554fa32776cda04b91ac5a26e9fc8de409bcb0

test:
  secret_key_base: 6ac4836124c668ef77af5ad64be92ad09d4f052cb32115342a10c0ed53ffa8998b834b83b85d52f69d9e8de4dc3d550e60cbe2e562e16495b7d7cf5867d8db3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
